# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Offline formats
formats:
  - pdf

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: docs/requirements.txt


build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_build:
      - |
        PDF_FILE_SRC="$READTHEDOCS_OUTPUT/pdf/openstream.pdf"
        PDF_FILE_DST="$READTHEDOCS_OUTPUT/html/files/OpenSTREAM.pdf"
        if [ -f  "$PDF_FILE_SRC" ]; then
          mkdir -p $READTHEDOCS_OUTPUT/html/files
          cp "$PDF_FILE_SRC" "$PDF_FILE_DST"
        fi